name: Delete All GitHub Releases and Tags

on:
  workflow_dispatch:

permissions:
  contents: write  # Diperlukan agar bisa menghapus tag dan release

jobs:
  delete_releases_tags:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install -y gh

      - name: Delete all releases
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for release in $(gh release list --limit 1000 | awk '{print $1}'); do
            echo "Deleting release: $release"
            gh release delete "$release" --yes
          done

      - name: Delete all remote tags
        run: |
          for tag in $(git ls-remote --tags origin | awk '{print $2}' | sed 's#refs/tags/##'); do
            echo "Deleting tag: $tag"
            git push origin :refs/tags/"$tag"
          done
